"""Private per-installation interception certificates and macOS trust setup."""

from __future__ import annotations

import os
import stat
import subprocess
from pathlib import Path

from mitmproxy.certs import CertStore


def prepare_certificate(directory: Path) -> Path:
    """Create or reuse a user-owned capture CA without sharing private keys.

    Args:
        directory: Dedicated capture certificate directory.

    Returns:
        Public certificate path suitable for the macOS trust store.

    Raises:
        ValueError: The directory or existing key material is not privately owned.
    """
    for ancestor in (directory, *directory.parents):
        if ancestor.is_symlink():
            raise ValueError(
                "Capture certificate directory must be a user-owned directory without links."
            )
    directory.mkdir(parents=True, mode=0o700, exist_ok=True)
    info = directory.lstat()
    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid():
        raise ValueError("Capture certificate directory must be a user-owned directory.")
    directory.chmod(0o700)
    for path in directory.iterdir():
        info = path.lstat()
        if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_nlink != 1:
            raise ValueError("Capture certificate directory contains unsafe files.")
        path.chmod(0o600)
    old_mask = os.umask(0o077)
    try:
        CertStore.from_store(str(directory), "mitmproxy", 2048)
    finally:
        os.umask(old_mask)
    return directory / "mitmproxy-ca-cert.pem"


def certificate_is_trusted(certificate: Path) -> bool:
    """Check the exact certificate with the macOS trust evaluator."""
    result = subprocess.run(
        ["/usr/bin/security", "verify-cert", "-c", str(certificate), "-p", "basic"],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        timeout=15,
        check=False,
    )
    return result.returncode == 0


def trust_certificate(certificate: Path) -> None:
    """Request administrator authorization for one local capture CA.

    Args:
        certificate: Public certificate generated by prepare_certificate.

    Raises:
        ValueError: Trust installation is declined or cannot be verified.
    """
    result = subprocess.run(
        [
            "/usr/bin/sudo",
            "/usr/bin/security",
            "add-trusted-cert",
            "-d",
            "-r",
            "trustRoot",
            "-p",
            "ssl",
            "-p",
            "basic",
            "-k",
            "/Library/Keychains/System.keychain",
            str(certificate),
        ],
        check=False,
        timeout=180,
        env={"PATH": "/usr/bin:/bin:/usr/sbin:/sbin"},
    )
    if result.returncode or not certificate_is_trusted(certificate):
        raise ValueError("Capture certificate trust was not installed. Run exp capture to retry.")
